---
# ===================================================================
# BUILD-TIME CONFIG PROPERTIES
#
# This is multi-env properties file. Keep sensitive data in external
# file that SysOps can source at runtime.
# ===================================================================


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# Paths
paths:
  src: app
  scripts:
    - "app/**/*.js"
    - "!app/require.config.js"
  images: "app/*/images/**/*.{png,gif,jpg,cur}"
  sass:
    - "app/**/*.scss"
    - "!app/common/styles/**/_*.scss"
  views: "app/*/views/**/*.html"
  fonts: "app/common/fonts/**/*"
  extras:
    - "app/.htaccess"
    - "app/config.yml"
    - "app/favicon.ico"
    - "app/robots.txt"
    - "app/**/*.json"
    - ".tmp/*/**/*.css"
    - "app/**/*.tpl.html"
  temp: .tmp
  dest: dist

# autoprefixer
autoprefixer:
  - "ie >= 10"
  - "ie_mob >= 10"
  - "ff >= 30"
  - "chrome >= 34"
  - "safari >= 7"
  - "opera >= 23"
  - "ios >= 7"
  - "android >= 4.4"
  - "bb >= 10"

# traceur
traceur:
  modules: amd
  atscript: true
  types: true
  typeAssertions: true
  typeAssertionModule: assert
  annotations: true
  memberVariables: true
  asyncFunctions: true
  asyncGenerators: true
  forOn: true
  arrayComprehension: true
  generatorComprehension: true
  experimental: true

# Require JS Bundler
buildProfile:
  mainConfigFile: app/require.config.js
  appDir: .tmp
  baseUrl: '.'
  removeCombined: true
  findNestedDependencies: true
  dir: dist
  optimizeCss: none
  optimize: none
  modules:
    - name: vendor
      exclude:
        - angular
    - name: bootstrap
      include:
        - requirejs
      exclude:
        - vendor
    - name: common/index
    - name: drug/index
    - name: experiments/index
    - name: home/index
    - name: provider/index

# Require JS Config : bowerRequireJS
AMD:
  baseUrl: ""
  transitive: true
  "exclude-dev": false
  config: app/require.config.js
  exclude:
    - bootstrap-sass-official
    - bootstrap
    - jquery

# ----------------------------------------
# TESTING PROPERTIES
# ----------------------------------------

# karma unit testing
karmaCommonConf:
  frameworks:
    - jasmine
    - requirejs
    - traceur
  files:
    - test/test-main.js
    - pattern: "app/**/*.js"
      included: false
    - pattern: "test/unit/**/*.js"
      included: false
    - pattern: "./bower_components/di/dist/amd/*.js"
      included: false
    - pattern: ./bower_components/assert/dist/amd/assert.js
      included: false
    - pattern: ./bower_components/diary/dist/amd/diary.js
      included: false
    - pattern: ./bower_components/harmony-reflect/reflect.js
      included: false
  exclude:
    - app/bootstrap.js
  proxies:
    /base/di/: /base/bower_components/di/dist/amd/
    /base/assert.js: /base/bower_components/assert/dist/amd/assert.js
    /base/diary.js: /base/bower_components/diary/dist/amd/diary.js
    /base/harmony-reflect.js: /base/bower_components/harmony-reflect/reflect.js
  reporters:
    - progress
  preprocessors:
    "app/**/*.js":
      - traceur
    "test/unit/**/*.js":
      - traceur
  browsers:
    - Chrome
  traceurPreprocessor:
    options:
      modules: amd
      atscript: true
      types: true
      typeAssertions: true
      typeAssertionModule: assert
      annotations: true
      memberVariables: true
      asyncFunctions: true
      asyncGenerators: true
      forOn: true
      arrayComprehension: true
      generatorComprehension: true
      experimental: true
